# #Python’s requests library makes it easy to communicate with APIs. >>> pip install modules
import requests


# #.get() >>> #A GET request is used to retrieve data.
# response = requests.get("https://jsonplaceholder.typicode.com/users") 

# print(response) #this contains everything giving by the server >>> json data, status_code, cookies, url etc
# print(response.status_code) #this will give us only status code

# #an API typically recieves json data
# response = requests.get("https://jsonplaceholder.typicode.com/users")
# data = response.json() #this changes json data into a python data structure
# print(type(data)) #this will print a list
# print(data)


# #.post() >>> POST is commonly used to send data to an API, often to create a new resource.

# url = "https://jsonplaceholder.typicode.com/posts"
# data = {
#     "name" : "Adnan",
#     "Age" : 25,
#     "userId" : 1
#         }
# reponse = requests.post(url, json=data) #this means send this data to server save the returned data in response
# print(response)
# print(reponse.json()) #this will give us the data and id = 101 which is generated by the API


# #.get() + query parameters
# try:
#     url = "https://api.example.come" #this is just an example url
#     params = {
#         "userId" : 1
#     }
#     repsonse = requests.get(url, params=params) #this will send the request with parameters like this url?userId=101
#     print(response)
# except Exception as e:
#     print(e)


# #Example
# url = "https://jsonplaceholder.typicode.com/posts"
# params = {
#     "userId" : 1
# }
# response = requests.get(url, params=params)
# print(response.status_code)
# print(response.json())


# #Headers >> Headers provide additional information(meta data) about a request. In Python, we pass headers using the headers= argument.
# try:
#     url = "https://api.example.com/users"
#     headers = { #we can have a single header as well as multiple headers
#         "Accept" : "application/json", #this says to the server what data format the request body contains
#         "Authorization" : "Bearer 'token_no'" #this gives a token to the server in case the server needs authorization
#     }
#     response = requests.get(url, headers)
#     print(response.status_code)
# except:
#     print("Error")


# #Request Body: The request body contains data that we send to the server. used with post, put, patch
# url = "https://jsonplaceholder.typicode.com/posts"
# data = {
#     "name" : "Adnan",
#     "Age" : 25,
#     "userId" : 1
#         }
# reponse = requests.post(url, json=data) #this send data as json in request body
# print(response.status_code)


# #response.json() >>> converts the recieved json data (response body) into a python data structure
# #response.text >>> converts the recieved json data (response body) into a string
# print(type(response.json()))
# print(type(response.text))


# #reponse.headers >>> response.headers contains the headers sent by the server.
# print(reponse.headers)


# #Complete example
# import requests

# url = "https://jsonplaceholder.typicode.com/posts"

# headers = {
#     "Accept": "application/json"
# }

# params = {
#     "userId": 1
# }

# response = requests.get(
#     url,
#     headers=headers,
#     params=params
# )

# print("Status:", response.status_code)
# print("Headers:", response.headers)
# print("Text:", response.text)

# data = response.json()

# print("JSON:", data)




## HTTP errors
## 400 → Bad Request
## 401 → Unauthorized
## 403 → Forbidden
## 404 → Not Found
## 500 → Server Error
## 503 → Service Unavailable

# #manually
# response = requests.get("https://jsonplaceholder.typicode.com/users/9999")

# if response.status_code == 200:
#     print(response.json())
# else:
#     print("Error...")
#     print("Response code: ",response.status_code)


# #or we can do
# try:
#     response = requests.get("https://jsonplaceholder.typicode.com/users/9999")
#     response.raise_for_status() #used for http errors like 404, 500 when we want the error go to except block
#     data = response.json()
#     print(data)
# except requests.exceptions.HTTPError as e:
#     print("ERROR: ", e)


# #timeout >>> Sometimes the server takes too long to respond. You should avoid allowing your program to wait forever.

# try: 
#     response = requests.get("https://jsonplaceholder.typicode.com/users/9999", timeout=0.1) #this means if the request takes more than 0.1 secs stop it
#     data = response.json()
#     print(data)
# except requests.exceptions.Timeout as e:
#     print("ERROR: ", e)



# #connection error >>> A connection error happens when Python cannot establish a connection to the server. Possible reasons could be :
# # - No internet connection
# # - Incorrect domain
# # - Server unavailable
# # - Network problem
# # - DNS problem
# try:
#     response = requests.get("https://thisdomaindoestnexist.com", timeout=2)
#     print(response.status_code())
# except requests.exceptions.ConnectionError as e:
#     print("ERROR: ", e)


# #Invalid Response: Even if the HTTP request succeeds, the response might not contain valid JSON.
# # if sometimes a server sends "server not available" instead of json response.json() will cause an error
# #here we can use exception ValueError


# #Example
# import requests

# try:
#     response = requests.get(
#         "https://jsonplaceholder.typicode.com/users",
#         timeout=5
#     )
#     response.raise_for_status()
#     print(response.json())
# except requests.exceptions.HTTPError:
#     print("HTTP ERROR")

# except requests.exceptions.ConnectionError:
#     print("Connection Error")

# except requests.exceptions.Timeout:
#     print("Timeout")

# except ValueError:
#     print("Wrong value")

# #Getting datasets from API >>>
# url = "https://jsonplaceholder.typicode.com/users"
# response = requests.get(url)
# response.raise_for_status()
# data = response.json()
# print(data)


# #Extracting json data
# print(data[0]["id"])
# print(data[0]["name"])

# for i in data:
#     print(i["name"])

# #nested json
# for i in data:
#     print(i["name"]+": ",i["address"]["street"])


#Pagination >>> APIs often have a large amount of data. Instead of returning 10,000 records in one response, an API may split them into smaller groups called pages.
url = "https://jsonplaceholder.typicode.com/posts"
response = requests.get(
    url, 
    params={"_page":1, "_limit":2} #this will help us get 2 elements[1,2] in page 1
    #params make the url like this : https://jsonplaceholder.typicode.com/posts?_page=1&_limit=2
    )
response.raise_for_status()
print(response.json())

print("------------------")

response = requests.get(
    url,
    params={"_page": 2, "_limit": 2}#this will help us get 2 elements[3,4] in page 2
)
response.raise_for_status()
print(response.json())

print("--------------------")

#we can use forloop to get this done one by one
for page in range(1,4):
    reponse = requests.get(url,
    params={"_page":page, "_limit": 4}
    )
    response.raise_for_status()
    print(reponse.json())
    print("-------------------------")

#Pagination is API-specific. So you always need to check that API’s documentation to know how its pagination works. here we used _page = 1 for some other API it could be page=1



#API authentication
